# IPL

In [1]:
from io import StringIO
import pandas as pd
import numpy as np

In [3]:
ipl = pd.read_csv('IPL.csv' , low_memory=False)

In [4]:
ipl.head()

,Unnamed: 0,match_id,date,match_type,event_name,innings,batting_team,bowling_team,over,ball,...,team_runs,team_balls,team_wicket,new_batter,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out
0,131970,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,...,1,1,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
1,131971,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,...,1,2,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
2,131972,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,...,2,2,0,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
3,131973,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,...,2,3,0,NaN,0,2,0,"('BB McCullum', 'SC Ganguly')",NaN,False
4,131974,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,...,2,4,0,NaN,0,3,0,"('BB McCullum', 'SC Ganguly')",NaN,False

In [7]:
ipl.columns

Index(['Unnamed: 0', 'match_id', 'date', 'match_type', 'event_name', 'innings',
       'batting_team', 'bowling_team', 'over', 'ball', 'ball_no', 'batter',
       'bat_pos', 'runs_batter', 'balls_faced', 'bowler', 'valid_ball',
       'runs_extras', 'runs_total', 'runs_bowler', 'runs_not_boundary',
       'extra_type', 'non_striker', 'non_striker_pos', 'wicket_kind',
       'player_out', 'fielders', 'runs_target', 'review_batter',
       'team_reviewed', 'review_decision', 'umpire', 'umpires_call',
       'player_of_match', 'match_won_by', 'win_outcome', 'toss_winner',
       'toss_decision', 'venue', 'city', 'day', 'month', 'year', 'season',
       'gender', 'team_type', 'superover_winner', 'result_type', 'method',
       'balls_per_over', 'overs', 'event_match_no', 'stage', 'match_number',
       'team_runs', 'team_balls', 'team_wicket', 'new_batter', 'batter_runs',
       'batter_balls', 'bowler_wicket', 'batting_partners', 'next_batter',
       'striker_out'],
      dtype='object')

In [177]:
ipl.iloc[0:3,10:30]

ipl['match_number']

0         Unknown
1         Unknown
2         Unknown
3         Unknown
4         Unknown
           ...
278200    Unknown
278201    Unknown
278202    Unknown
278203    Unknown
278204    Unknown
Name: match_number, Length: 278205, dtype: object

## Highest Run Getter

In [21]:
most_runs = ipl.groupby('batter')['runs_batter'].sum().sort_values(ascending=False)

In [25]:
most_runs.head(1)

batter
V Kohli    8671
Name: runs_batter, dtype: int64

In [27]:
print("Highest run getter in IPL History is \n",most_runs.head(1))

Highest run getter in IPL History is
 batter
V Kohli    8671
Name: runs_batter, dtype: int64

## Highest Wicket Taker

In [28]:
most_wickets =  ipl.groupby('bowler')['bowler_wicket'].sum().sort_values(ascending=False)

In [29]:
most_wickets

bowler
YS Chahal        221
B Kumar          198
PP Chawla        192
SP Narine        192
R Ashwin         187
                ...
RA Shaikh          0
CK Kapugedera      0
RA Tripathi        0
JE Root            0
C Ganapathy        0
Name: bowler_wicket, Length: 550, dtype: int64

In [30]:
most_wickets.head(1)

bowler
YS Chahal    221
Name: bowler_wicket, dtype: int64

In [31]:
print("Highest wicket taker in IPL History is \n",most_wickets.head(1))

Highest wicket taker in IPL History is
 bowler
YS Chahal    221
Name: bowler_wicket, dtype: int64

## Highest Strike Rate of Batsman

In [71]:
ttl_runs = ipl.groupby('batter')['runs_batter'].sum()
ttl_ball_faced = ipl.groupby('batter')['balls_faced'].sum()

mask = ttl_runs > 300

runs_filtered = ttl_runs[mask]
balls_filtered = ttl_ball_faced[mask]

sr = (runs_filtered / balls_filtered) * 100

highest_SR = sr.sort_values(ascending=False)

In [72]:
highest_SR

batter
J Fraser-McGurk    199.481865
Priyansh Arya      182.274247
Naman Dhir         180.645161
PD Salt            175.707155
AD Russell         174.098361
                      ...
SC Ganguly         106.809184
Lalit Yadav        105.172414
CA Pujara           99.744246
B Kumar             91.168091
A Mishra            90.930788
Length: 199, dtype: float64

## Best economy bowlers (min 200 balls)

In [107]:
df_valid = ipl[ipl['valid_ball'] == 1]
ttl_ball_bowled = df_valid.groupby('bowler')['ball'].count().sort_values(ascending=False)
ttl_runs_conced = ipl.groupby('bowler')['runs_bowler'].sum().sort_values(ascending=False)

ttl_overs= (ttl_ball_bowled/6)

mask = ttl_ball_bowled>300
ttl_runs_conced_final = ttl_runs_conced[mask]
ttl_overs_final = ttl_overs[mask]

economy = ttl_runs_conced_final/ttl_overs_final

best_eco = economy.sort_values(ascending = True)

In [108]:
best_eco

bowler
A Kumble              6.578238
GD McGrath            6.611111
M Muralitharan        6.698953
RE van der Merwe      6.744921
DL Vettori            6.787645
                       ...
Akash Madhwal        10.056818
Kartik Tyagi         10.137441
Vijaykumar Vyshak    10.378378
Mukesh Kumar         10.396226
Yash Thakur          10.428894
Length: 198, dtype: float64

## Most sixes and fours by players

In [118]:
df = ipl[ipl['runs_batter'] == 6]
df1 = ipl[ipl['runs_batter'] == 4]

most_sixes = df.groupby('batter')['runs_batter'].count().sort_values(ascending=False)
most_fours = df1.groupby('batter')['runs_batter'].count().sort_values(ascending=False)
most_sixes.head(20)

most_fours.head(20)

batter
V Kohli           774
S Dhawan          768
DA Warner         663
RG Sharma         640
AM Rahane         515
SK Raina          506
G Gambhir         492
RV Uthappa        481
KD Karthik        466
SA Yadav          454
KL Rahul          453
F du Plessis      440
AB de Villiers    414
JC Buttler        408
CH Gayle          408
SV Samson         379
SR Watson         377
MS Dhoni          375
Shubman Gill      372
PA Patel          365
Name: runs_batter, dtype: int64

## Orange Cap winner per season

In [133]:
all_batter_inaSeason = ipl.groupby(['season' , 'batter'])['runs_batter'].sum().reset_index(name = 'total_runs_inASeason')

all_batter_inaSeason

idx = all_batter_inaSeason.groupby('season')['total_runs_inASeason'].idxmax()

org_cap = all_batter_inaSeason.loc[idx]

In [134]:
org_cap

       season           batter  total_runs_inASeason
115   2007/08         SE Marsh                   616
229      2009        ML Hayden                   572
446   2009/10     SR Tendulkar                   618
502      2011         CH Gayle                   608
684      2012         CH Gayle                   733
910      2013       MEK Hussey                   733
1088     2014       RV Uthappa                   660
1148     2015        DA Warner                   562
1383     2016          V Kohli                   973
1422     2017        DA Warner                   641
1594     2018    KS Williamson                   735
1694     2019        DA Warner                   692
1866  2020/21         KL Rahul                   676
2051     2021       RD Gaikwad                   635
2144     2022       JC Buttler                   863
2423     2023     Shubman Gill                   890
2606     2024          V Kohli                   741
2640     2025  B Sai Sudharsan                   759

# Purple Cap winner per season

In [ ]:
all_bowler_inaSeason = ipl.groupby(['season','bowler'])['bowler_wicket'].sum().reset_index(name = 'total_wickets_inASeason')

all_bowler_inaSeason

idx = all_bowler_inaSeason.groupby('season')['total_wickets_inASeason'].idxmax()

purple_cap = all_bowler_inaSeason.loc[idx]
purple_cap

## Which team has won the most matches?

In [199]:
matches = ipl[['match_id', 'match_won_by']].drop_duplicates()

matches

        match_id                 match_won_by
0         335982        Kolkata Knight Riders
225       335983          Chennai Super Kings
473       335984             Delhi Daredevils
692       335985  Royal Challengers Bangalore
938       335986        Kolkata Knight Riders
...          ...                          ...
277070   1473507  Royal Challengers Bengaluru
277314   1473508  Royal Challengers Bengaluru
277461   1473509               Mumbai Indians
277709   1473510                 Punjab Kings
277953   1473511  Royal Challengers Bengaluru

[1169 rows x 2 columns]

In [202]:
df = matches['match_won_by'].value_counts().reset_index(name='won_matches')

In [203]:
df

                   match_won_by  won_matches
0                Mumbai Indians          151
1           Chennai Super Kings          142
2         Kolkata Knight Riders          135
3   Royal Challengers Bangalore          114
4              Rajasthan Royals          114
5           Sunrisers Hyderabad           93
6               Kings XI Punjab           85
7              Delhi Daredevils           67
8                Delhi Capitals           51
9                Gujarat Titans           37
10                 Punjab Kings           34
11         Lucknow Super Giants           30
12              Deccan Chargers           29
13                      Unknown           23
14  Royal Challengers Bengaluru           18
15                Gujarat Lions           13
16                Pune Warriors           12
17       Rising Pune Supergiant           10
18         Kochi Tuskers Kerala            6
19      Rising Pune Supergiants            5

In [209]:
matches1 = ipl[['match_id', 'batting_team', 'bowling_team']].drop_duplicates()

matches1

        match_id                 batting_team                 bowling_team
0         335982        Kolkata Knight Riders  Royal Challengers Bangalore
124       335982  Royal Challengers Bangalore        Kolkata Knight Riders
225       335983          Chennai Super Kings              Kings XI Punjab
349       335983              Kings XI Punjab          Chennai Super Kings
473       335984             Rajasthan Royals             Delhi Daredevils
...          ...                          ...                          ...
277585   1473509               Gujarat Titans               Mumbai Indians
277709   1473510               Mumbai Indians                 Punjab Kings
277835   1473510                 Punjab Kings               Mumbai Indians
277953   1473511  Royal Challengers Bengaluru                 Punjab Kings
278082   1473511                 Punjab Kings  Royal Challengers Bengaluru

[2333 rows x 3 columns]

In [210]:
df1 = matches1['batting_team'].value_counts().reset_index(name='played_matches')

In [211]:
df1

                   batting_team  played_matches
0                Mumbai Indians             277
1         Kolkata Knight Riders             264
2           Chennai Super Kings             251
3   Royal Challengers Bangalore             240
4              Rajasthan Royals             234
5           Sunrisers Hyderabad             195
6               Kings XI Punjab             190
7              Delhi Daredevils             161
8                Delhi Capitals             105
9               Deccan Chargers              75
10                 Punjab Kings              74
11               Gujarat Titans              60
12         Lucknow Super Giants              58
13                Pune Warriors              45
14                Gujarat Lions              30
15  Royal Challengers Bengaluru              30
16       Rising Pune Supergiant              16
17      Rising Pune Supergiants              14
18         Kochi Tuskers Kerala              14

In [217]:
df['win_per'] = df['won_matches'] / df1['played_matches']

In [218]:
df

                   match_won_by  won_matches   win_per
0                Mumbai Indians          151  0.545126
1           Chennai Super Kings          142  0.537879
2         Kolkata Knight Riders          135  0.537849
3   Royal Challengers Bangalore          114  0.475000
4              Rajasthan Royals          114  0.487179
5           Sunrisers Hyderabad           93  0.476923
6               Kings XI Punjab           85  0.447368
7              Delhi Daredevils           67  0.416149
8                Delhi Capitals           51  0.485714
9                Gujarat Titans           37  0.493333
10                 Punjab Kings           34  0.459459
11         Lucknow Super Giants           30  0.500000
12              Deccan Chargers           29  0.500000
13                      Unknown           23  0.511111
14  Royal Challengers Bengaluru           18  0.600000
15                Gujarat Lions           13  0.433333
16                Pune Warriors           12  0.750000
17       Rising Pune Supergiant           10  0.714286
18         Kochi Tuskers Kerala            6  0.428571
19      Rising Pune Supergiants            5       NaN

⚡ Level 2: Match & Team Insights
Which team has won the most matches?
Use: match_won_by
Win percentage of each team
Matches played vs matches won
Impact of toss decision
Does choosing batting/fielding affect winning?
Performance by venue
Which stadium favors batsmen vs bowlers?
Average score per match
Use team_runs
Highest successful run chase


🧠 Level 3: Advanced Player Analysis (Real DS Work)
Player consistency (average runs per match)
Most clutch players
Runs in death overs (16–20)
Best finishers
High strike rate in last 5 overs
Powerplay specialists
Performance in overs 1–6
Most dot balls by bowlers
runs_total == 0
Batting position analysis
Avg runs by bat_pos


🔥 Level 4: Ball-by-Ball Intelligence (Advanced)
Which over gives most runs?
Group by over
Wicket distribution by over
Partnership analysis
Use batting_partners
Most dangerous bowler vs specific batsman
Head-to-head stats
Bowler vs batsman dismissal frequency


📊 Level 5: Real Portfolio-Level Projects
Build a “Player Rating System”
Combine:
Strike rate
Average
Consistency
Predict match winner (ML Project)
Features:
Toss
Venue
Team strength
Win probability during match
Ball-by-ball prediction
Best XI of IPL (Data-driven)
Team strategy analysis
Bat first vs chase success rate